// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWpYcdBIGHTg9zv_u7Gq214rLtOR-F1vU',
    appId: '1:265296158854:web:190c79bae945c9ab5c3107',
    messagingSenderId: '265296158854',
    projectId: 'ai-todo-3ab7f',
    authDomain: 'ai-todo-3ab7f.firebaseapp.com',
    storageBucket: 'ai-todo-3ab7f.firebasestorage.app',
    measurementId: 'G-0F58HSMQCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATLg8Nq9bXGtooBD2TeZvbBZzMLD9txnM',
    appId: '1:265296158854:android:928a4ba6d459439f5c3107',
    messagingSenderId: '265296158854',
    projectId: 'ai-todo-3ab7f',
    storageBucket: 'ai-todo-3ab7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1XY9rerVKe-Ive8FXOcsSdADegUzq3T0',
    appId: '1:265296158854:ios:8ace604ea6acf3875c3107',
    messagingSenderId: '265296158854',
    projectId: 'ai-todo-3ab7f',
    storageBucket: 'ai-todo-3ab7f.firebasestorage.app',
    iosBundleId: 'com.example.aiTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1XY9rerVKe-Ive8FXOcsSdADegUzq3T0',
    appId: '1:265296158854:ios:8ace604ea6acf3875c3107',
    messagingSenderId: '265296158854',
    projectId: 'ai-todo-3ab7f',
    storageBucket: 'ai-todo-3ab7f.firebasestorage.app',
    iosBundleId: 'com.example.aiTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWpYcdBIGHTg9zv_u7Gq214rLtOR-F1vU',
    appId: '1:265296158854:web:fffc39b7405a8cb05c3107',
    messagingSenderId: '265296158854',
    projectId: 'ai-todo-3ab7f',
    authDomain: 'ai-todo-3ab7f.firebaseapp.com',
    storageBucket: 'ai-todo-3ab7f.firebasestorage.app',
    measurementId: 'G-GVPH9VWHZZ',
  );
}
